export type ChaosChallenge = {
  code: string;
  name: string;
  category: "4xx" | "5xx" | "network";
  difficulty: 1 | 2 | 3;
  hint: string;
  url: string;
  method: string;
  cause: string;
  fix: string;
  color: string;
};

export const CHAOS_CATALOG: ChaosChallenge[] = [
  {
    code: "400",
    name: "Bad Request",
    category: "4xx",
    difficulty: 1,
    hint: "Send an invalid age to the mortality API. Try a negative number.",
    url: "/api/mortality?age=-5",
    method: "GET",
    cause: "The server rejected the request because a parameter was invalid. Age must be 0-100.",
    fix: "Validate inputs before sending. Check API docs for allowed ranges.",
    color: "#f59e0b",
  },
  {
    code: "401",
    name: "Unauthorized",
    category: "4xx",
    difficulty: 1,
    hint: "Call the chaos endpoint requesting a 401. No auth header needed to trigger it.",
    url: "/api/chaos?code=401",
    method: "GET",
    cause: "The server requires authentication but no credentials were provided.",
    fix: "Include an Authorization header with a valid API key or token.",
    color: "#f59e0b",
  },
  {
    code: "403",
    name: "Forbidden",
    category: "4xx",
    difficulty: 1,
    hint: "Even with credentials, some resources are off-limits. Trigger a 403.",
    url: "/api/chaos?code=403",
    method: "GET",
    cause: "You authenticated, but your account lacks permission for this resource.",
    fix: "Check your API key's scope and permissions. Contact the API provider.",
    color: "#f59e0b",
  },
  {
    code: "404",
    name: "Not Found",
    category: "4xx",
    difficulty: 1,
    hint: "Request a URL that doesn't exist. The chaos endpoint can return a 404 for you.",
    url: "/api/chaos?code=404",
    method: "GET",
    cause: "The URL path does not match any endpoint on the server. This is the most common API error, usually caused by a typo in the URL or a deleted resource.",
    fix: "Check the URL for typos. Verify the endpoint exists in the API docs. Pay attention to path segments and version numbers.",
    color: "#f59e0b",
  },
  {
    code: "405",
    name: "Method Not Allowed",
    category: "4xx",
    difficulty: 2,
    hint: "Send a POST request to an endpoint that only accepts GET.",
    url: "/api/chaos",
    method: "POST",
    cause: "The HTTP method (POST) is not supported by this endpoint.",
    fix: "Use the correct method (GET, POST, PUT, DELETE) as specified in the docs.",
    color: "#f59e0b",
  },
  {
    code: "418",
    name: "I'm a Teapot",
    category: "4xx",
    difficulty: 2,
    hint: "An Easter egg from 1998. Ask the chaos endpoint for code 418.",
    url: "/api/chaos?code=418",
    method: "GET",
    cause: "The server is a teapot and refuses to brew coffee. (RFC 2324, an April Fools' joke that became real.)",
    fix: "Use a coffee pot instead. Or just enjoy that this status code exists.",
    color: "#f59e0b",
  },
  {
    code: "422",
    name: "Unprocessable",
    category: "4xx",
    difficulty: 2,
    hint: "Send a well-formed request with semantically wrong data.",
    url: "/api/chaos?code=422",
    method: "GET",
    cause: "The syntax is correct but the data doesn't make sense. Like requesting age=200.",
    fix: "Check that values are semantically valid, not just syntactically correct.",
    color: "#f59e0b",
  },
  {
    code: "429",
    name: "Rate Limited",
    category: "4xx",
    difficulty: 3,
    hint: "Send more than 5 requests within 5 seconds to the chaos endpoint.",
    url: "/api/chaos?code=429",
    method: "RAPID",
    cause: "You exceeded the rate limit. The server protects itself from being overwhelmed.",
    fix: "Implement exponential backoff. Respect the Retry-After header.",
    color: "#f59e0b",
  },
  {
    code: "500",
    name: "Server Error",
    category: "5xx",
    difficulty: 2,
    hint: "Trigger an internal server error via the chaos endpoint.",
    url: "/api/chaos?code=500",
    method: "GET",
    cause: "Something broke inside the server. This is never the client's fault.",
    fix: "Retry after a short delay. If persistent, report the issue to the API provider.",
    color: "#ef4444",
  },
  {
    code: "503",
    name: "Service Unavailable",
    category: "5xx",
    difficulty: 2,
    hint: "The server is temporarily down for maintenance.",
    url: "/api/chaos?code=503",
    method: "GET",
    cause: "The server is overloaded or under maintenance. Temporary outage.",
    fix: "Wait and retry. Implement circuit breaker patterns for production systems.",
    color: "#ef4444",
  },
  {
    code: "408",
    name: "Timeout",
    category: "network",
    difficulty: 3,
    hint: "Set a short client timeout against a slow server. The chaos endpoint supports delays.",
    url: "/api/chaos?code=408&delay=3000",
    method: "TIMEOUT",
    cause: "The server took too long to respond. The client gave up waiting.",
    fix: "Set appropriate timeout values. Show loading states. Implement retry logic.",
    color: "#8b5cf6",
  },
  {
    code: "CORS",
    name: "CORS Block",
    category: "network",
    difficulty: 3,
    hint: "Request the chaos endpoint with nocors=true. The browser will block it.",
    url: "/api/chaos?nocors=true",
    method: "CORS",
    cause: "The server didn't include CORS headers, so the browser blocked the response for security.",
    fix: "Configure Access-Control-Allow-Origin on the server. Or use a backend proxy.",
    color: "#8b5cf6",
  },
];
